apiVersion: apps/v1
# the kind of object we are creating is a Deployment
kind: Deployment
metadata:
  # the name of the Deployment
  name: ubuntu-sleeper-deployment
  # create the deployment in the test namespace
  namespace: test
# the specification of the pod we want to create
spec:
  # the number of replicas we want to have
  replicas: 3
  # the selector is used to identify the pods that are part of this replicaset
  selector:
    matchLabels:
      # the replicas will identify the pods that are part of this replicaset if they have the labels app: nginx
      app: ubuntu-sleeper
  # the pod template that we want to use
  template:
    metadata:
      labels:
        app: ubuntu-sleeper
    spec:
      containers:
          # the name of the container
        - name: ubuntu-sleeper
          # the image we want to use
          # ubuntu-sleeper is a custom image that sleeps for 3600 seconds and then exits
          image: ubuntu-sleeper
          #if we uncomment this it will override the default command of the image with the command below
          # command: ["ls"]
          # the arguments we want to pass to the container when it starts so that will sleep for 10 seconds
          args: ["10"]
          # the port we want to expose
          ports:
          - containerPort: 80
          
# command vs args
# command is the default command of the image that we want to use and args are the arguments we want to pass to the command when the container starts
# if we don't specify the command it will use the default entrypoint of the image
# if we don't specify the args it will use the default CMD of the image

