apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
    # Readiness probe configuration
    readinessProbe:
      # Exec command to the pod
      exec:
        # Command to check if the pod is ready
        command:
          - cat
          - /tmp/healthy
 
