apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
    # Readiness probe configuration
    readinessProbe:
      # HTTP GET request to the pod 
      httpGet:
        # Path to check if the pod is ready
        path: /index.html
        # Port to check
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
