apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd:latest
          resources:
            limits:
              memory: 200Mi
          volumeMounts:
            - name: storage-volume
              mountPath: /var/log/fluentd
            - name: fluentd-config
              mountPath: /fluentd/etc/fluentd.conf
              subPath: fluentd-config.yaml  # Mount the ConfigMap as a file
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: fluentd-pvc
        - name: fluentd-config
          configMap:
            name: fluentd-config  # Reference the ConfigMap created earlier
