apiVersion: v1
kind: PersistentVolume
metadata:
  name: fluentd-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ~/Desktop/linux/K8s/apps/mo

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluentd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: fluentd
