apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemo
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
    spec: 
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name : elasticsearch
          image: k8s.gcr.io/fluentd-elasticsearch:1.20
          