apiVersion: apps/v1
kind: Deployment
metadata :
   name : "deploy"
spec:
  replicas: 7
  selector:
   matchLabels:
     dev: web
  template:
    metadata:
      labels:
        dev: web
    spec:
      containers:
        - name: web
          image: ubuntu
          ports:
           - containerPort: 80
