apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi


    ClaimName:  pvc-storage