# apiVersion: v1
# kind: Pod
# metadata: 
#   name: web
# spec: 
#   volumes: # add a volumes list
#   - name: myvolume  # just a name, you'll reference this in the pods
#     configMap:
#       name: cmvolume
#   containers:
#   - name: nginx
#     image: nginx
#     volumeMounts:
#     - name: myvolume
#       mountPath: /etc/luka



# --- 

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    securityContext:
      runAsUser: 0