apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-{{ .Release.Name }} 
  # namespace: {{ .Release.Namespace | default "default"}}
  labels:
{{- range $x,$y := .Values.labels }}
    {{ $x }}: {{ $y | quote }}
{{- end }}
    moner: apporkelm
spec:
  replicas: 3
  selector:
    matchLabels:
      {{- include "labels" . | indent 6 }}
  template:
    metadata:
      labels:
      {{- include "labels" . | indent 6 }}
    spec:
      containers:
      - name: nginx
        image: nginx
{{- if eq .Values.resources "true" }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits: 
            memory: "128Mi"
            cpu: "500m"
{{- else if eq .Values.resources "false"}}
        resources:
          requests:
            memory: "20Mi"
            cpu: "80m"
          limits: 
            memory: "40Mi"
            cpu: "100m"
{{- end }}
{{- if   .Values.image.pullPolicy  }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- else   }}
        imagePullPolicy: Always 
{{- end }}