apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.app.name | quote  }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31005
      name: {{ randAlpha 10 | lower }}
    # - port: 90
    #   targetPort: http
    #   protocol: TCP
    #   name:   {{ randAlpha 10 | lower }}
  selector:
    {{- include "labels" . | indent 4 }}
# {{- with .Values.app }}
#   {{- with .ui }}
#     background: {{ .bg }}
#     frontground: {{ .fg }}
#   {{- end }}
#     database: {{ .db.name  | quote }}
#     connction: {{ .db.conn }}
#     release: {{ $.Release.Name }}
# {{- end}}
