apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    livenessProbe: 
      initialDelaySeconds: 5 #  it is set to 5 seconds, which means that Kubernetes will wait for 5 seconds after the container starts before initiating the first liveness probe check. 
      periodSeconds: 5 # This means that every 5 seconds, Kubernetes will send a request to the container's specified liveness endpoint to determine if it is still healthy.
      exec: 
        command: 
        - ls 
  restartPolicy: Never