apiVersion: v1
kind: Pod
metadata:
 name: myapp-pod
spec:
 containers:
 - name: nginx-container
   image: nginx
 tolerations:
 - key: "spray"
   operator: "Equal"
   value: "mortein"
   effect: "NoSchedule"