print ("I'll show to U some cool view >")

print("       ♥♥♥♥     ♥♥♥♥")
print("    ♥♥♥      ♥♥♥      ♥♥♥")
print("  ♥♥♥         ♥         ♥♥♥")
print(" ♥♥♥                      ♥♥♥")
print("♥♥♥                         ♥♥♥")
print(" ♥♥♥                       ♥♥♥")
print("  ♥♥♥                     ♥♥♥")
print("    ♥♥♥                 ♥♥♥")
print("      ♥♥♥             ♥♥♥")
print("        ♥♥♥         ♥♥♥")
print("          ♥♥♥     ♥♥♥")
print("             ♥♥♥♥♥")

print ('this view for special users!')

print("     ♥♥♥♥♥♥♥♥♥     ♥♥♥♥♥♥♥♥♥")
print("  ♥♥♥♥         ♥♥♥♥ ♥♥♥♥         ♥♥♥♥")
print("♥♥♥              ♥♥♥♥              ♥♥♥")
print("♥♥♥                                 ♥♥♥")
print("♥♥♥                                  ♥♥♥")
print("♥♥♥                                   ♥♥♥")
print(" ♥♥♥                                  ♥♥♥")
print("  ♥♥♥                                 ♥♥♥")
print("    ♥♥♥                              ♥♥♥")
print("      ♥♥♥                          ♥♥♥")
print("        ♥♥♥                      ♥♥♥")
print("           ♥♥♥                 ♥♥♥")
print("             ♥♥♥             ♥♥♥")
print("               ♥♥♥         ♥♥♥")
print("                 ♥♥♥     ♥♥♥")
print("                   ♥♥♥ ♥♥♥")
print("                     ♥♥♥")