apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      type: front
  template:
    metadata:
        labels:
          app: myapp
          type: front
    spec:
        containers:
          - name: nginx-app
            image: nginx:alpine
            ports:
              - containerPort: 80


