apiVersion: v1
kind: Namespace
metadata:
  name:  my-app-namespace

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
  namespace:  my-app-namespace
data:
  APP_PORT: "8080"


--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-app-deployment
  namespace: my-app-namespace

spec:   
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name : pyapp
          image: khaledhawil/pyapp:1.2.0
          ports:
           - containerPort: 8080
          env:
            - name : APP_PORT
              valueFrom:
                configMapKeyRef: 
                  name : my-app-config
                  key: APP_PoRT

--- 

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: my-app-namespace
spec: 
  selector:
    app : myapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
 

--- 

apiVersion: v1
kind: Node
metadata:
  name : my-app-node
  annotations:
    node.alpha.kubernetes.io/ttl: "0"

soec:
  taints:
    - key: app
      value: myapp
      effect: NoSchedule

  
  
  




