# ex-2
# Run Pod with a web service (e.g. httpd)
# Verify the web service is running with the ps command
# Kill the web service process -

apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
    - name: httpd-container
      image: nginx
      ports: 
        - containerPort: 80

#
#
