apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "replica-set-1"
  labels:
    test: "busybox"


spec:
  replicas: 3
  selector:
   matchLabels: 
    test: "busybox"
  template:
    metadata:
      name: "replica-set-1"
      labels:
        test: "busybox"
    spec:
      containers:
        - name : "replica-set-1"
          image : busybox
          
      
    
    