
# Vagrant.configure("2") do |config|

#   # Define the Kubernetes nodes
#   config.vm.define "master" do |master|
#     master.vm.box = "ubuntu/focal64"
#     master.vm.hostname = "master"
#     master.vm.network "private_network", ip: "192.168.56.1"
#     master.vm.provider "virtualbox" do |v|
#       v.memory = 2048
#       v.cpus = 2
#     end
#   end

#   config.vm.define "worker" do |worker|
#     worker.vm.box = "ubuntu/focal64"
#     worker.vm.hostname = "worker"
#     worker.vm.network "private_network", ip: "192.168.57.1"
#     worker.vm.provider "virtualbox" do |v|
#       v.memory = 2048
#       v.cpus = 2
#     end
#   end

# end

# Vagrant.configure("2") do |config|
#   config.vm.box = "ubuntu/focal"

#   config.vm.define "master" do |master|
#     master.vm.hostname = "master"
#     master.vm.network "private_network", ip: "192.168.56.2"

#     master.vm.provider "virtualbox" do |vb|
#       vb.memory = "2048"
#       vb.cpus = "2"
#     end

#     master.vm.provision "shell", inline: <<-SHELL
#       # Install Docker
#       apt-get update
#       apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
#       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#       add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#       apt-get update
#       apt-get install -y docker-ce docker-ce-cli containerd.io

#       # Install Kubernetes components
#       curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
#       echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
#       apt-get update
#       apt-get install -y kubelet kubeadm kubectl
#     SHELL

#     master.vm.provision "shell", inline: <<-SHELL
#       # Initialize Kubernetes master
#       kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.33.10

#       # Copy kubeconfig to user's home directory
#       mkdir -p /home/vagrant/.kube
#       cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
#       chown vagrant:vagrant /home/vagrant/.kube/config

#       # Install Flannel network plugin
#       kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
#     SHELL
#   end

#   config.vm.define "worker" do |worker|
#     worker.vm.hostname = "worker"
#     worker.vm.network "private_network", ip: "192.168.56.3"

#     worker.vm.provider "virtualbox" do |vb|
#       vb.memory = "2048"
#       vb.cpus = "2"
#     end

#     worker.vm.provision "shell", inline: <<-SHELL
#       # Install Docker
#       apt-get update
#       apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
#       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#       add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#       apt-get update
#       apt-get install -y docker-ce docker-ce-cli containerd.io

#       # Install Kubernetes components
#       curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
#       echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
#       apt-get update
#       apt-get install -y kubelet kubeadm kubectl
#     SHELL

#     # worker.vm.provision "shell", inline: <<-SHELL
#     #   # Join Kubernetes cluster
#     #   kubeadm join 192.168.33.10:6443 --token <token> --discovery-token-ca-cert-hash <hash>
#     # SHELL
#   end
# end

# wlp3s0

Vagrant.configure("2") do |config|

  # Define the Kubernetes master
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/focal64"
    master.vm.hostname = "master"
    master.vm.network "public_network", bridge: "wlp3s0: Wi-Fi (DODO U)"
    master.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  #   # Install Kubernetes master components
  #   master.vm.provision "shell", inline: <<-SHELL
  #     curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  #     echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  #     sudo apt-get update
  #     sudo apt-get install -y kubelet kubeadm kubectl
  #   SHELL
  end

  # Define the Kubernetes worker
  config.vm.define "worker" do |worker|
    worker.vm.box = "ubuntu/focal64"
    worker.vm.hostname = "worker"
    worker.vm.network "public_network", bridge: "wlp3s0: Wi-Fi (DODO U)"
    worker.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  #   # Install Kubernetes worker components
  #   worker.vm.provision "shell", inline: <<-SHELL
  #     curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  #     echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  #     sudo apt-get update
  #     sudo apt-get install -y kubelet kubeadm kubectl
  #   SHELL
  end

end
